# Dependencies
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins: 		[jekyll-sitemap, jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            'brontolabs'
tagline:          'Improvise. Adapt. Overcome. Interlace.'
description:      'brontosaurusrex.github.io'
url:              http://brontosaurusrex.github.io

author:
  name:           'brontosaurusrex'
  url:            http://brontosaurusrex.github.io

paginate:         7

# collections https://jekyllrb.com/docs/step-by-step/09-collections/

collections:
    bucentaur:
        output: true
